-- Create database
CREATE DATABASE CSM;
GO

-- Use the CSM database
USE CSM;
GO

-- Drop the ACCOUNT table if it exists
IF OBJECT_ID('dbo.ACCOUNT', 'U') IS NOT NULL
    DROP TABLE dbo.ACCOUNT;
GO

-- Create tables
CREATE TABLE EMPLOYEE
(
    EMPLOYEE_ID VARCHAR(15) PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR(25) NOT NULL,
    EMPLOYEE_PASSWORD CHAR(8) NOT NULL,
    EMPLOYEE_CONTACT CHAR(11) NOT NULL,
    EMPLOYEE_ADDRESS VARCHAR(50) NOT NULL,
    EMPLOYEE_EMAIL VARCHAR(25) UNIQUE NOT NULL,
    EMPLOYEE_DESIGNATION VARCHAR(15) NOT NULL,
    EMPLOYEE_HIREDATE DATE NOT NULL,
    EMPLOYEE_FIREDATE DATE,
    EMPLOYEE_STATUS VARCHAR(10) NOT NULL,
    EMPLOYEE_SALES INT
);
GO

CREATE TABLE MANUFACTURER
(
    MANUFACTURER_ID VARCHAR(15) PRIMARY KEY,
    MANUFACTURER_NAME VARCHAR(25) NOT NULL,
    MANUFACTURER_EMAIL VARCHAR(25) UNIQUE NOT NULL,
    MANUFACTURER_ADDRESS VARCHAR(50) NOT NULL,
    MANUFACTURER_CONTACT CHAR(11) NOT NULL
);
GO

CREATE TABLE CUSTOMER
(
    CUSTOMER_CNIC CHAR(13) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(25) NOT NULL,
    CUSTOMER_CONTACT CHAR(13) NOT NULL,
    CUSTOMER_ADDRESS VARCHAR(50) NOT NULL
);
GO

CREATE TABLE CAR
(
    CAR_ID VARCHAR(15) PRIMARY KEY,
    CAR_NAME VARCHAR(20) NOT NULL,
    CAR_MODEL CHAR(4) NOT NULL,
    CAR_COMPANY VARCHAR(15) NOT NULL,
    CAR_STATUS VARCHAR(10) NOT NULL,
    CAR_PRICE INT NOT NULL
);
GO

CREATE TABLE MANUF_ORDER
(
    ORDER_ID VARCHAR(15) PRIMARY KEY,
    EMPLOYEE_ID VARCHAR(15) REFERENCES EMPLOYEE(EMPLOYEE_ID),
    CAR_ID VARCHAR(15) REFERENCES CAR(CAR_ID),
    MANUFACTURER_ID VARCHAR(15) REFERENCES MANUFACTURER(MANUFACTURER_ID),
    ORDER_DATE DATE NOT NULL,
    BILL INT NOT NULL
);
GO

CREATE TABLE STOCK
(
    ORDER_ID VARCHAR(15) REFERENCES MANUF_ORDER(ORDER_ID),
    CAR_ID VARCHAR(15) REFERENCES CAR(CAR_ID),
    REC_DATE DATE NOT NULL
);
GO

CREATE TABLE CUSTOMER_ORDER
(
    ORDER_ID VARCHAR(15) PRIMARY KEY,
    EMPLOYEE_ID VARCHAR(15) REFERENCES EMPLOYEE(EMPLOYEE_ID),
    CAR_ID VARCHAR(15) REFERENCES CAR(CAR_ID),
    CUSTOMER_CNIC CHAR(13) REFERENCES CUSTOMER(CUSTOMER_CNIC),
    ORDER_DATE DATE NOT NULL,
    BILL INT NOT NULL
);
GO

CREATE TABLE STOCK_PAYMENT
(
    ORDER_ID VARCHAR(15) REFERENCES MANUF_ORDER(ORDER_ID),
    PAYMENT_DATE DATE NOT NULL
);
GO

CREATE TABLE SELL_PAYMENT
(
    ORDER_ID VARCHAR(15) REFERENCES CUSTOMER_ORDER(ORDER_ID),
    PAYMENT_DATE DATE NOT NULL
);
GO

CREATE TABLE ACCOUNT
(
    MANF_ORDER VARCHAR(15) REFERENCES MANUF_ORDER(ORDER_ID),
    CUST_ORDER VARCHAR(15) REFERENCES CUSTOMER_ORDER(ORDER_ID),
    AMOUNT INT,
    IS_PAID VARCHAR(5) NOT NULL,
    PAYMENT_DATE DATE NOT NULL
);
GO

-- Insert data into EMPLOYEE table
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, EMPLOYEE_PASSWORD, EMPLOYEE_CONTACT, EMPLOYEE_ADDRESS, EMPLOYEE_EMAIL, EMPLOYEE_DESIGNATION, EMPLOYEE_HIREDATE, EMPLOYEE_STATUS, EMPLOYEE_SALES)
VALUES ('SM123', 'Faisal', '999480', '03137721207', 'Hafizabad', 'faisal@gmail.com', 'Salesman', CONVERT(DATE, GETDATE()), 'Working', 0);

INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, EMPLOYEE_PASSWORD, EMPLOYEE_CONTACT, EMPLOYEE_ADDRESS, EMPLOYEE_EMAIL, EMPLOYEE_DESIGNATION, EMPLOYEE_HIREDATE, EMPLOYEE_STATUS, EMPLOYEE_SALES)
VALUES ('MG999', 'Ahmad', '999480', '03076821561', 'Lahore', 'ahmad@gmail.com', 'Manager', CONVERT(DATE, GETDATE()), 'Working', 0);

-- Insert data into CAR table
INSERT INTO CAR (CAR_ID, CAR_NAME, CAR_MODEL, CAR_COMPANY, CAR_STATUS, CAR_PRICE)
VALUES ('C1356', 'Model X', '2020', 'Tesla', 'Available', 2500000);

INSERT INTO CAR (CAR_ID, CAR_NAME, CAR_MODEL, CAR_COMPANY, CAR_STATUS, CAR_PRICE)
VALUES ('C1245', 'Z4', '2019', 'BMW', 'Available', 4500000);

-- Insert data into CUSTOMER table
INSERT INTO CUSTOMER (CUSTOMER_CNIC, CUSTOMER_NAME, CUSTOMER_CONTACT, CUSTOMER_ADDRESS)
VALUES ('1273648292039', 'FAISAL', '12345543213', 'LAHORE');

-- Insert data into EMPLOYEE table again (MG999 entry)
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, EMPLOYEE_PASSWORD, EMPLOYEE_CONTACT, EMPLOYEE_ADDRESS, EMPLOYEE_EMAIL, EMPLOYEE_DESIGNATION, EMPLOYEE_HIREDATE, EMPLOYEE_STATUS, EMPLOYEE_SALES)
VALUES ('MG999', 'Ahmad', '999480', '03076821561', 'Lahore', 'ahmad@gmail.com', 'Manager', CONVERT(DATE, GETDATE()), 'Working', 0);

-- Insert data into CAR table (additional entry)
INSERT INTO CAR (CAR_ID, CAR_NAME, CAR_MODEL, CAR_COMPANY, CAR_STATUS, CAR_PRICE)
VALUES ('C3241', 'GLB', '2020', 'Mercedes', 'Available', 3500000);

-- Insert data into MANUFACTURER table
INSERT INTO MANUFACTURER (MANUFACTURER_ID, MANUFACTURER_NAME, MANUFACTURER_CONTACT, MANUFACTURER_EMAIL, MANUFACTURER_ADDRESS)
VALUES ('MF123', 'MERCEDES', '23456789087', 'nkwjdnck@gmail.com', 'London');

-- Insert data into MANUF_ORDER table
INSERT INTO MANUF_ORDER (ORDER_ID, EMPLOYEE_ID, CAR_ID, MANUFACTURER_ID, ORDER_DATE, BILL)
VALUES ('MOD123', 'MG999', 'C3241', 'MF123', GETDATE(), 3555000);

-- Insert data into STOCK_PAYMENT table
INSERT INTO STOCK_PAYMENT (ORDER_ID, PAYMENT_DATE)
VALUES ('MOD123', GETDATE());

-- Insert data into STOCK table
INSERT INTO STOCK (ORDER_ID, REC_DATE)
VALUES ('MOD123', GETDATE());

-- Insert data into ACCOUNT table
INSERT INTO ACCOUNT (MANF_ORDER, AMOUNT, IS_PAID, PAYMENT_DATE)
VALUES ('MOD123', 3500000, 'TRUE', GETDATE());


INSERT INTO CUSTOMER_ORDER(ORDER_ID,EMPLOYEE_ID,CAR_ID,CUSTOMER_CNIC,ORDER_DATE,BILL)
Values('COD123','MG999','C1245','1273648292039',GETDATE(),3355000)
Go 
INSERT INTO ACCOUNT (CUST_ORDER, AMOUNT, IS_PAID, PAYMENT_DATE)
VALUES ('COD123', 3355000, 'FALSE', GETDATE());
Go
